version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync . "s3://mitchfitzsimmons.com" --delete
 post_build:
   commands:
     - echo "post_build step"
     - aws cloudfront create-invalidation --distribution-id "E1XONVQ01154VW" --paths /* index.html comments.html future.html past.html websystems.css images/*